### PR TITLE
Raising errors for missing M or nshots

### LINKED ISSUE #73: Revisiting `run_circuit` arguments
We should avoid setting defaults to `nshots` and `device`. In particular, `nshots` should be mandatory only if the circuit contains a M gate, otherwise it must be empty (and raise an error otherwise).

### PR DESCRIPTION
**Pull request by BrunoLiegiBastonLiegi**
As per title, errors are raised when running on hardware and either:
- no measurements are present in the circuit
- `nshots` is not defined

this should close #73 

At the moment I am just checking whether `device == "k2"`, but ideally it would be nice if each partition had a property, `simulation=True` for instance, doing the check on the node inside the job and returning an error response.

### CODE REVIEW

**Comment by scarrazza** [comment]
Okay, that is a good point in favor of moving this check to the front end. @marcorossi5, could you please show @BrunoLiegiBastonLiegi how to change the front-end API and include this feature?

**Comment by marcorossi5** [comment]
Moving the logic to the webapp means adding the checks in this function: https://github.com/qiboteam/qibo-webapp/blob/892ee98d36d777873a1c713d3c92b8beade19cd6/src/client/views.py#L75

**Comment by BrunoLiegiBastonLiegi** [comment]
Now that qiboteam/qibo-webapp#105 implemented the blocking of circuit without measurements or `nshots` specified, this PR probably reduces to just some minor additions to the docstrings, and setting `nshots=None` by default. I am not sure whether we are supposed to test here as well that `run_circuit` returns a `403` response in those cases.

**Comment by scarrazza** [comment]
Thanks @BrunoLiegiBastonLiegi . I think we should make the `device` mandatory (i.e. remove the default value).

**Comment by scarrazza** [comment]
Thanks @BrunoLiegiBastonLiegi, could you please double check if the README and sphinx docs are okay with your latest changes?

**Comment by BrunoLiegiBastonLiegi** [comment]
The `README` is showing an example with the `sim` partition (btw, this should be changed to `k2` now, right?), thus it should be fine. The docs at the moment seem to consist in basically just the dosctrings from the source code, which I modified already, so nothing to do there as well.

**Comment by scarrazza** [comment]
Thanks, I would suggest to do not state any device name here and just point to the user that in order to device the device name, visit the cloud system and checkout the available partitions for his account.

**Pull request merged**
