### PR TITLE
Add `initial_state` to `_post_circuit`

### PR DESCRIPTION
**Pull request by MatteoRobbiati**

### CODE REVIEW

**Review by marcorossi5 — COMMENTED** [review]
Thanks @MatteoRobbiati. The changes are clear.
Could you let me know how these should be handled on the webapp side?

**Comment by scarrazza** [comment]
The initial state is the first argument when executing a circuit (before the nshots option).

**Comment by marcorossi5** [comment]
I see. How do you want to pass it to Django? JSON? If np.ndarray is an option you might want to serialize to bytes with pickle. My question is: is it safe to execute pickled objects received from http requests?

**Comment by scarrazza** [comment]
That is a good point, @MatteoRobbiati does ibmq supports this feature? Usually passing initial states are not possible for hardware execution. If this is the case we should not support this feature.

**Comment by alecandido** [comment]
> If np.ndarray is an option you might want to serialize to bytes with pickle.

There is a safe (and portable way) to serialize NumPy arrays to bytes, i.e. [`np.save`](https://numpy.org/doc/stable/reference/generated/numpy.save.html#numpy.save).

Unfortunately, it is writing to a file-like object, so you have to do a little bit of gymnastics to get it in memory (without passing through disk), but it's not terrible.
It's something like:
```py
import io

buffer = io.BytesIO()
np.save(buffer, myarray)
buffer.seek(0)
mybytes = buffer.read()
```
and `io` is standard library.

I didn't check it, but if that doesn't work should be something very close.

**Comment by alecandido** [comment]
> Usually passing initial states are not possible for hardware execution.

For hardware, the only way would be to disassemble it as a circuit, isn't it?

**Comment by scarrazza** [comment]
Indeed, so given that the major goal of this project is to execute on quantum hardware, we should give up on this setup which might be even more complex, i.e. if a crazy users decides to send 1TB of state vector...

**Comment by MatteoRobbiati** [comment]
I agree with the direction you suggested. Together with @BrunoLiegiBastonLiegi we tested the Qiskit backend and it seems they adopt the "hardware-like" approach (circuits as input, frequencies as output). 
Fine with closing this and, then, we should just remove the `initial_state` argument from the `qibo-cloud-backend/qibo_client.py`,

**Comment by scarrazza** [comment]
Thanks @MatteoRobbiati for checking, please go ahead with changes in the qibo-cloud-backends.

**Pull request closed without merging**
