### PR TITLE
Postpone environment evaluation

### LINKED ISSUE #29: Top-level environment probe
Environment variables are in general dynamical, and they could change their value between the `import` time and the execution, and even between various executions.

So, this approach is not suitable for retrieving them:
https://github.com/qiboteam/qibo-client/blob/4e70c049bb66475d9af468fe3e9611d75fd5e5fb/src/qibo_client/tii.py#L5-L7
as it was found in https://github.com/qiboteam/qibo-cloud-backends/pull/11#discussion_r1510195513

### PR DESCRIPTION
**Pull request by alecandido**
At the moment, I shifted this to the `Client()` instantiation.

It could be better to pass down the callable, and only retrieve the URL during the request.
I didn't do it, because there might be a point in having a consistent `Client`, during its whole lifetime (though I'm not sure...).

Closes #29

### CODE REVIEW

**Comment by alecandido** [comment]
Btw, you're mixing `unittest` and `pytest`, that are two separate testing frameworks.

https://github.com/qiboteam/qibo-client/blob/4e70c049bb66475d9af468fe3e9611d75fd5e5fb/tests/test_tii.py#L1
(and Pytest is the runner).

I'd suggest using https://docs.pytest.org/en/latest/how-to/monkeypatch.html

**Review by scarrazza — APPROVED** [review]
This is fine by me, even though from a practical perspective it is very unlikely that we will need this feature when we will have a stable setup.

**Comment by alecandido** [comment]
> This is fine by me, even though from a practical perspective it is very unlikely that we will need this feature when we will have a stable setup.

Hopefully true, but it could happen that someone wants to patch the port after import (that almost always happens top-level). True that, since the port is fixed server-side, there should be no reason to patch the provider. But it is also useful as a blueprint for other ones (and it should not be harmful).

**Review by marcorossi5 — APPROVED** [review]

**Comment by marcorossi5** [comment]
> Btw, you're mixing `unittest` and `pytest`, that are two separate testing frameworks.
> 
> https://github.com/qiboteam/qibo-client/blob/4e70c049bb66475d9af468fe3e9611d75fd5e5fb/tests/test_tii.py#L1
> 
> 
> (and Pytest is the runner).
> I'd suggest using https://docs.pytest.org/en/latest/how-to/monkeypatch.html

Let's merge for the moment and open a refactoring issue about that.

**Pull request merged**
